---
- name: "verify radosgw_interface exists on {{ inventory_hostname }}"
  fail:
    msg: "{{ radosgw_interface }} does not exist on {{ inventory_hostname }}"
  when:
    - radosgw_interface not in ansible_interfaces

- name: "verify radosgw_interface is active on {{ inventory_hostname }}"
  fail:
    msg: "{{ radosgw_interface }} is not active on {{ inventory_hostname }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + radosgw_interface]['active'] == "false"

- name: "verify radosgw_interface has an ip v4 on {{ inventory_hostname }}"
  fail:
    msg: "{{ radosgw_interface }} does not have any IPv4 address on {{ inventory_hostname }}"
  when:
    - ip_version == "ipv4"
    - hostvars[inventory_hostname]['ansible_' + radosgw_interface]['ipv4'] is not defined

- name: "verify radosgw_interface has an ip v6 on {{ inventory_hostname }}"
  fail:
    msg: "{{ radosgw_interface }} does not have any IPv6 address on {{ inventory_hostname }}"
  when:
    - ip_version == "ipv6"
    - hostvars[inventory_hostname]['ansible_' + radosgw_interface]['ipv6'] is not defined