---
- name: create filesystem pools
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool create {{ item.name }} {{ item.pgs }} {{ item.type | default('') }}"
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"
  with_items:
    - "{{ cephfs_pools }}"

- name: set erasure coding test profile
  command: "ceph osd erasure-code-profile set default plugin=lrc mapping=DD layers='[ [ 'DDc', '""' ] ]' crush-locality=osd crush-failure-domain=osd --force"
  with_items:
  - "{{ cephfs_pools }}"
  when:
  - common_single_host_mode == true
  - item.type is defined
  - item.type == "erasure"

- name: allow erasure coding overwrites
  command: "ceph osd pool set {{ item.name }} allow_ec_overwrites true"
  with_items:
  - "{{ cephfs_pools }}"
  when:
  - item.type is defined
  - item.type == "erasure"

- name: check if ceph filesystem already exists
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} fs get {{ cephfs }}"
  register: check_existing_cephfs
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"
  failed_when: false

- name: create ceph filesystem
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} fs new {{ cephfs }} {{ cephfs_metadata }} {{ cephfs_data }}"
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when:
    - check_existing_cephfs.rc != 0

- name: assign application to cephfs pools
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} osd pool application enable {{ cephfs_data }} {{ cephfs }}"
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when:
    - check_existing_cephfs.rc != 0
    - ceph_release_num[ceph_release] >= ceph_release_num['luminous']

- name: allow multimds
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} fs set {{ cephfs }} allow_multimds true --yes-i-really-mean-it"
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when:
    - ceph_release_num[ceph_release] == ceph_release_num.luminous

- name: set max_mds
  command: "{{ hostvars[groups[mon_group_name][0]]['docker_exec_cmd'] | default('') }} ceph --cluster {{ cluster }} fs set {{ cephfs }} max_mds {{ mds_max_mds }}"
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when:
    - ceph_release_num[ceph_release] >= ceph_release_num.jewel
    - mds_max_mds > 1
