---
- name: enable erasure coded test mode
  block:
    - command: "ceph osd getcrushmap -o /root/ansible_crush_map_compressed"
      args:
        chdir: /root
        creates: /root/ansible_crush_map_compressed
    - command: "crushtool -d /root/acrush_map_compressed -o /root/ansible_crush_map_decompressed"
      args:
        chdir: /root
        creates: /root/ansible_crush_map_decompressed
    - replace:
        path: /root/ansible_crush_map_decompressed
        regexp: "step chooseleaf indep 0 type host"
        replace: "step chooseleaf indep 0 type osd"
    - command: "crushtool -c crush_map_decompressed -o /root/ansible_new_crush_map_compressed"
      args:
        chdir: /root
        creates: /root/ansible_new_crush_map_decompressed
    - command: "ceph osd setcrushmap -i /root/ansible_new_crush_map_compressed"
      args:
        chdir: /root
    - command: "ceph osd pool set {{ item }} allow_ec_overwrites true"
    - command: "ceph osd pool set {{ item }} min_size 1"
    - command: "ceph osd erasure-code-profile set default plugin=lrc k=1 m=1 l=1 crush-locality=host crush-failure-domain=osd"
    - file:
        path: /root/ansible_new_crush_map_decompressed
        state: absent
    - file:
        path: /root/ansible_crush_map_compressed
        state: absent
